name: Daily commit

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Make empty commit
        run: |
          git config user.email "youremail@gmail.com"
          git config user.name "Your Name"
          git commit --allow-empty -m "daily update"
          git push